version: '3.8'

services:
  redis-server:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --requirepass 123
    volumes:
      - redis_data:/data
